import '../../core/api_call.dart';
import '../../core/api_client.dart';
import '../models/briefing.dart';

/// GET /api/briefing — the morning briefing, generated by Nemotron Ultra.
class BriefingRepository {
  const BriefingRepository(this._client);

  final ApiClient _client;

  /// [force] bypasses the server's per-day cache so Ultra regenerates it.
  Future<Briefing> fetch({bool force = false}) => apiCall(() async {
        final response = await _client.dio.get<Object?>(
          '/api/briefing',
          queryParameters: force ? {'force': '1'} : null,
        );
        return Briefing.fromJson(asJsonObject(response.data));
      });
}
